; До 7 ГБ на файл (должны совпадать с client_max_body_size в nginx)
upload_max_filesize = 7G
post_max_size = 7G
max_execution_time = 3600
max_input_time = 3600
memory_limit = 1024M
max_file_uploads = 20

; Важно для Livewire/Filament при больших файлах
file_uploads = On
max_input_vars = 3000
