server {
    listen 80;
    listen  [::]:80;
    listen  443 ssl;

    # При 502 (PHP-FPM перезапущен) или 503 показываем заглушку вместо стандартной ошибки nginx
    error_page 502 503 =503 /503.html;

    client_max_body_size 7G;
    ssl_certificate     /etc/nginx/certs/fullchain.pem;
    ssl_certificate_key /etc/nginx/certs/privkey.pem;
    index index.php index.html;
    error_log  /var/log/nginx/error.log;
    access_log /var/log/nginx/access.log;
    root /var/www/public;
    location ~ \.php$ {
        try_files $uri =404;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass app-vehicles:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
        fastcgi_read_timeout 7200;  # до 2 ч для загрузок до 7 ГБ
        fastcgi_send_timeout 7200;
        fastcgi_connect_timeout 300;
    }
    location / {
        try_files $uri $uri/ /index.php?$query_string;
        gzip_static on;
    }
}
